version: "3.8"
services:
  api-server:
    build: ./backend   
    container_name: node-api
    restart: always
    ports:
      - "4000:4000"
    volumes: 
      - ./backend:/usr/src/app
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge
